# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
      name: Rust project
      strategy:
        matrix:
          os: [ ubuntu-latest, macOS-latest, windows-latest ]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - name: check
          run: cargo check --all
        - uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release --all-features
        - uses: actions-rs/cargo@v1
          with:
            command: test
            args: --show-output

  static_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check clippy
        run: rustup component add clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D clippy::all
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Check for panics
        run: ./tests/nopanic.ci

